const Actions = {
  ADD_PRODUCT_TO_STORE:"ADD_PRODUCT_TO_STORE",
  ADD_ALL_DATA_TO_STORE: "ADD_ALL_DATA_TO_STORE",
  ADD_MASSAGE_TO_STORE: "ADD_MASSAGE_TO_STORE",
  REMOVE_MASSAGE_TO_STORE: "REMOVE_MASSAGE_TO_STORE",
  REMOVE_All_MASSAGES_TO_STORE: "REMOVE_All_MASSAGES_TO_STORE",
  ADD_ORDER_TO_STORE: "ADD_ORDER_TO_STORE",
  REMOVE_ORDER_TO_STORE: "REMOVE_ORDER_TO_STORE",
  REMOVE_ALL_ORDERS_TO_STORE: "REMOVE_ALL_ORDERS_TO_STORE",
};
export default Actions;
